### ISSUE TITLE
known bugs!!

### ISSUE THREAD

**Issue by Sycosean217** [TheRealRyukiro/Project-Zero#3]
sorry that answer not an answer prints twice
encounters  still don't have conditions meaning they can still be cherry picked unknow logic bug

**Comment by TheRealRyukiro** [comment]
![image](https://user-images.githubusercontent.com/14095035/129307166-bc2b1bf8-5ca6-4103-95fd-7bbfc1109aa2.png)

Cherry Picking fixed but now it prints the catch twice as shown in the attached image. Closing & Opening a new issue. This is lower priority
